// apps/vue/src/pages/PageHome.vue
<template>
  <div class="text-center">
    <h1 class="mt-8">Home Page: {{ firstName }}</h1>
    <p>Powered by VueJS, ReactJS, LitElement</p>
    <p class="text-yellow-500">styled by: Tailwind CSS</p>
    <br />
    <a href="/react"
      >go to ReactJS
      <button
        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
      >
        Button
      </button>
    </a>
    <br />

    <br />
    <router-link to="/page1">
      <a>Vue Router: Go to Page 1</a>
      <button
        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
      >
        Button
      </button>
    </router-link>
    <br/>
    <p class="mt-12">button created fron btn class</p>
    <button class="btn btn-blue">BTN Button</button>
  </div>
</template>

<script>
export default {
  name: "p-home",
  data() {
    return {
      firstName: "Micro Frontend"
    };
  }
};
</script>

// apps/react/pages/PageHome.js
import React from "react";

import Editor from "../components/Editor";
// import logo from "../images/2.jpg";

const HomePage = () => {
  return (
    <div className="text-center">
      <h1>BLOG SECTION</h1>
      <p>power by ReactJS</p>
      <p className="mt-12">Test render image:</p>
      {/* <img className="w-1/4 m-auto" src={logo} /> */}

      <br />
      <a href="/">
        <button className="btn btn-blue mr-4"> Go Home </button>
      </a>

      <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
        Tailwind Button
      </button>

      <Editor />
      
    </div>
  );
};

export default HomePage;
